### PR TITLE
Update model

### PR DESCRIPTION
**Pull request by tsurumeso**

### CODE REVIEW

**Comment by aufr33** [comment]
Fine. But why is the model size now 30 mb? I hope I don't lose anything compared to version 2.2?

**Comment by tsurumeso** [comment]
That's because the model architecture has been updated.
The new model achieved higher quality with smaller model sizes.

**Comment by aufr33** [comment]
@tsurumeso Could you tell us more about your new model? Is it the same MMDenseNet or something else?

**Comment by tsurumeso** [comment]
The overall architecture is a combination of several DeepLabv3-like modules.
And using Multi-scale and Multi-band methods from MMDenseNet.

**Pull request merged**
